#!/bin/bash

openssl req -new -sha256 -nodes -out $1.csr -newkey rsa:2048 -keyout $1.key -config <( cat config/$1.csr.cnf )
openssl x509 -req -in $1.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out $1.crt -days 500 -sha256 -extfile config/$1.ext

